name: GitHub-Profile-3D-Contribution

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "10 16 * * *"
  workflow_dispatch:

jobs:
  update-profile-3d-contribution:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: settings/season.json

      - name: Commit & Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A .
          git commit -m "generated"
          git push
